# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

# Departing from the implicit _user.c scheme
XDP_TARGETS  := xdp_prog_kern_port
USER_TARGETS := xdp_load_and_stats_port

LIBBPF_DIR = ../dependencies/libbpf/src/
COMMON_DIR = ../dependencies/common/
PROTOCOL_DIR = ../protocol/

include $(COMMON_DIR)/common.mk

